package com.kubelin.springsoap.vo.boxoffice2;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-04-24T01:29:02.581+09:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://www.kobis.or.kr/kobisopenapi", name = "BoxOfficeAPIService")
@XmlSeeAlso({ObjectFactory.class})
public interface BoxOfficeAPIService {

    @WebMethod
    @RequestWrapper(localName = "searchWeeklyBoxOfficeList", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "com.kubelin.springsoap.vo.boxoffice2.SearchWeeklyBoxOfficeList")
    @ResponseWrapper(localName = "searchWeeklyBoxOfficeListResponse", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "com.kubelin.springsoap.vo.boxoffice2.SearchWeeklyBoxOfficeListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.kubelin.springsoap.vo.boxoffice2.WeeklyBoxOfficeResult searchWeeklyBoxOfficeList(

        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "targetDt", targetNamespace = "")
        java.lang.String targetDt,
        @WebParam(name = "itemPerPage", targetNamespace = "")
        java.lang.String itemPerPage,
        @WebParam(name = "weekGb", targetNamespace = "")
        java.lang.String weekGb,
        @WebParam(name = "multiMovieYn", targetNamespace = "")
        java.lang.String multiMovieYn,
        @WebParam(name = "repNationCd", targetNamespace = "")
        java.lang.String repNationCd,
        @WebParam(name = "wideAreaCd", targetNamespace = "")
        java.lang.String wideAreaCd
    ) throws OpenAPIFault;

    @WebMethod
    @RequestWrapper(localName = "searchDailyBoxOfficeList", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "com.kubelin.springsoap.vo.boxoffice2.SearchDailyBoxOfficeList")
    @ResponseWrapper(localName = "searchDailyBoxOfficeListResponse", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "com.kubelin.springsoap.vo.boxoffice2.SearchDailyBoxOfficeListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.kubelin.springsoap.vo.boxoffice2.DailyBoxOfficeResult searchDailyBoxOfficeList(

        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "targetDt", targetNamespace = "")
        java.lang.String targetDt,
        @WebParam(name = "itemPerPage", targetNamespace = "")
        java.lang.String itemPerPage,
        @WebParam(name = "multiMovieYn", targetNamespace = "")
        java.lang.String multiMovieYn,
        @WebParam(name = "repNationCd", targetNamespace = "")
        java.lang.String repNationCd,
        @WebParam(name = "wideAreaCd", targetNamespace = "")
        java.lang.String wideAreaCd
    ) throws OpenAPIFault;
}
