package com.kubelin.springsoap.vo.boxoffice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-04-23T23:12:01.602+09:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "BoxOfficeAPIServiceImplService",
                  wsdlLocation = "http://www.kobis.or.kr/kobisopenapi/webservice/soap/boxoffice?wsdl",
                  targetNamespace = "http://service.boxoffice.server.apiservice.kobisopenapi/")
public class BoxOfficeAPIServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplService");
    public final static QName BoxOfficeAPIServiceImplPort = new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.kobis.or.kr/kobisopenapi/webservice/soap/boxoffice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BoxOfficeAPIServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://www.kobis.or.kr/kobisopenapi/webservice/soap/boxoffice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoxOfficeAPIServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BoxOfficeAPIServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BoxOfficeAPIService
     */
    @WebEndpoint(name = "BoxOfficeAPIServiceImplPort")
    public BoxOfficeAPIService getBoxOfficeAPIServiceImplPort() {
        return super.getPort(BoxOfficeAPIServiceImplPort, BoxOfficeAPIService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoxOfficeAPIService
     */
    @WebEndpoint(name = "BoxOfficeAPIServiceImplPort")
    public BoxOfficeAPIService getBoxOfficeAPIServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BoxOfficeAPIServiceImplPort, BoxOfficeAPIService.class, features);
    }

}
